services:
  mail-worker:
    build: .
    container_name: mail-worker
    env_file:
      - .env
      - .env.secrets
    environment:
      BROKER_HOST: rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - 3080:3080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    volumes:
      - ./src/templates:/worker/src/templates
      - ./src/config:/worker/src/config
    networks:
      - production
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - production
networks:
  production:
